// UI-only localization. Simulation state and gesture timing remain unchanged.
(()=>{
 const pairs=[
 ['开启摄像头','Enable camera'],['记录张开','Calibrate open palm'],['记录握拳','Calibrate fist'],['用鼠标模拟','Mouse simulation'],['重新识别双手','Reset hand tracking'],
 ['预览绕行效果','Preview vortex'],['切回手势控制','Hand control'],['预览炸散','Preview burst'],['预览60把排剑','Preview 60 swords'],['预览递增批次穿行','Preview flight'],['预览托球巨剑合击','Preview orb attack'],
 ['本地音乐（自备授权音频）','Local music (use licensed audio)'],['录制剑阵、自选音乐和右下角摄像头小窗，不包含按钮或网页文字','Record the effect, local music and camera inset; exclude page controls and text'],
 ['● 开始录制','● Record'],['■ 停止并保存','■ Stop and save'],['下载原始录像','Download WebM'],['下载 MP4','Download MP4'],['剑阵＋摄像头','Effect + camera'],
 ['正在保存…','Saving…'],['此浏览器不支持录制，请使用 Chrome','Recording is unavailable; please use Chrome'],['录制出错，请重试','Recording failed; try again'],['未录到画面，请重试','No frames recorded; try again'],['正在本机转换 MP4，请勿关闭页面…','Converting to MP4 locally; keep this page open…'],['WebM 已生成 · 本机运行可转换 MP4','WebM ready · Run locally for MP4 conversion'],['MP4 转换失败，原始录像已保留。请通过本地 serve.py 服务打开页面后再录制。','MP4 conversion failed; WebM retained. Run serve.py locally for MP4 export.'],['MP4 已生成 · 可发送微信','MP4 ready · Share via WeChat'],['无法开始录制：','Cannot start recording: '],
 ['等待摄像头','Waiting for camera'],['摄像头已开启','Camera enabled'],['摄像头打开失败：','Camera failed: '],['加载中…','Loading…'],['重试','Retry'],['鼠标模拟关闭','Mouse simulation off'],['把右手或左手举到镜头前','Raise either hand in front of the camera'],['左手已识别 · 掌心朝上托球','Left hand detected · Turn palm upward to hold the orb'],
 ['第二次巨剑散开后解锁 · 单食指保持 → 龙卷 · 移动 → 凝成 2400 把绕行剑阵 · 正面旋风（单模式） · 五指张开炸散 · 摊掌2秒排剑，移动食指3、6、9把递增跟随','After releasing the second giant sword: hold index finger → vortex; move → 2,400-sword flow. Open palm to burst. Hold palm open for 2s → 60 swords; move index finger → batches of 3, 6, 9…'],
 ['按住左键 = 攥拳 · 滚轮调收拢度（≥88% 保持 3 秒 → 全场吸引）· 按住左键时按住 S = 两指慢慢伸出凝巨剑（松开 S = 慢慢缩回）· 松开左键 = 快速张开（炸开）· 按住时滚轮慢慢减到底 = 慢慢张开 · 不按左键时按住 A = 剑阵手势（松开 A = 万剑齐发；要先有小飞剑）· 剑阵排满后按住 A 再按 D = 剑指往下一挥（万剑下斩 → 剑涡）· ← → = 剑的方向 · ↑ ↓ = 漩涡前后翻 · 0 复位','Hold left mouse = fist; wheel = grip strength (≥88% for 2.5s attracts all). Hold S with left mouse = form giant sword; release S = retract. Release mouse = burst; scroll grip down slowly = gentle release. Hold A without mouse = formation; release A = launch (requires small swords). Once formed, A + D = downward attack. ← → direction; ↑ ↓ tilt; 0 reset.'],
 ['摊掌排剑 · 60把中剑凝结中（2秒）','Open-palm formation · Forming 60 swords (2s)'],['60把中剑就绪 · 伸食指穿行 · 收拳退出','60 swords ready · Point to fly · Close fist to exit'],['摊掌排剑 · 60把中等飞剑，两秒凝结','Open-palm formation · 60 swords forming in 2s'],['先摊掌排剑，等待两秒凝结完成','Preview 60 swords first; allow 2 seconds to form'],['食指引导穿行 · 3、6、9把递增中剑化为小剑','Fingertip flight · Batches of 3, 6, 9… split into small swords'],['剑流穿行展示 · 随后托球合击','Sword-flow preview · Orb attack follows'],['已退出排剑模式','Formation mode ended'],['已切回手势 · 第二次巨剑散开后可单食指召唤','Hand control · Release the second giant sword to unlock index-finger summoning'],
 ['剑尖抵球 · 高速钻旋 · 雷霆合击','Tip against orb · High-speed drill · Lightning attack'],['球面雷霆 · 巨剑合击炸裂','Orb lightning · Giant-sword burst'],['第二次巨剑完成 · 已解锁左手托球与600把剑阵','Second giant sword complete · Left-hand orb and 600-sword formation unlocked'],
 ['单食指龙卷 · 移动食指绕行，五指张开炸散','Index-finger vortex · Move to guide; open palm to burst'],['2400 把中等飞剑 · 单食指绕行 · 五指张开炸散','2,400 swords · Guide with index finger · Open palm to burst'],['单食指龙卷 · 移动后凝成 2400 把剑 · 五指张开炸散','Index-finger vortex · Move to form 2,400 swords · Open palm to burst'],['小飞剑汇聚成 2400 把中等飞剑','Small swords gathering into 2,400 medium swords'],['小飞剑汇聚 · 2400 把中等飞剑绕行','Small swords gathering · 2,400 medium swords in flight'],['2400 把飞剑沿弯曲路线绕行','2,400 swords following a curved path'],['上宽下窄龙卷','Vortex with a broad top and narrow base'],['预览中','Preview'],
 ['万剑下斩 — 剑往下冲、边走边出剑','Downward attack — swords launch while moving'],['龙卷（移动手势 = 整体移动 · 攥拳 = 卷回 · 快速张开 = 万剑齐发）','Vortex (move hand = move formation; fist = retract; open quickly = launch)'],['剑阵（剑指往下一挥 = 万剑下斩 · 快速张开 = 万剑齐发 · 收拳 = 卷回漩涡）','Formation (flick sword fingers down = downward attack; open quickly = launch; fist = retract)'],['几何长剑（张开手掌 = 碎成小剑）','Geometric sword (open palm = split into small swords)'],['巨剑（张开手掌 = 碎成飞剑）','Giant sword (open palm = split into flying swords)'],
 ['围球剑阵 · 左手托球移动，右手张开释放','Orb formation · Move left palm to guide; open right palm to release'],['右手靠近金球形成围球剑阵','Bring right hand near the orb to form surrounding swords'],['左手金光球','Left-hand golden orb'],['第二次巨剑完成后解锁托球','Orb unlocks after the second giant sword'],['全场飞剑汇聚 · 3秒成阵','All swords gathering · Forms in 3s'],['600 把围球剑阵 · 捏近增强，张开放远','600-sword orb formation · Pinch closer to intensify; open to expand'],['双手张开 · 雷霆炸裂','Both palms open · Lightning burst'],['捏合召剑 · 600 把','Pinch to summon · 600 swords'],
 ['五指张开 · 全场剑流炸散','Open palm · Burst the entire sword flow'],['五指张开 · 龙卷炸散','Open palm · Vortex burst'],['突然摊掌 · 全场炸开','Sudden open palm · Burst everything'],['两指慢慢伸出 — 凝结几何长剑','Extend two fingers slowly — form geometric sword'],['缩回 — 散回漩涡','Retract — return to vortex'],['剑指 — 凝成几何长剑','Sword fingers — form geometric sword'],['剑指 — 凝剑中','Sword fingers — forming sword'],['剑指 — 凝剑','Sword fingers — form sword'],['剑阵手势（还没有小飞剑：先攥拳凝巨剑、再张开碎成飞剑）','Formation gesture (no small swords yet: form a giant sword, then open palm to split it)'],['剑指下挥 — 万剑下斩','Flick sword fingers down — downward attack'],['剑阵还没排满（排满再往下挥）','Formation incomplete (wait before flicking down)'],['收回剑指','Retract sword fingers'],['万剑齐发','Launch all swords'],['巨剑炸成飞剑','Giant sword bursts into flying swords'],['巨剑散成飞剑','Giant sword disperses into flying swords'],['手丢了 — 剑阵散开','Hand lost — formation disperses'],['手丢了 — 巨剑散开','Hand lost — giant sword disperses'],['剑阵散开','Formation disperses'],['慢慢散开','Gentle release'],['全场吸引中','Attracting all particles'],['全场吸引','Attract all particles'],['收拢 — 吸引中','Closed — gathering'],['张开 — 自由','Open — free'],['炸开','Burst'],
 ['穿行中 · ','In flight · '],[' / 60把中剑依次分解 · 收拳退出',' / 60 swords released · Close fist to exit'],['剑尖抵球 · ','Tip against orb · '],['秒 · 高速钻旋','s · High-speed drill'],['左手托球蓄力 · ','Left-palm orb charge · '],['🌀 剑阵 — 凝剑 ','🌀 Formation — forming '],['🌀 剑阵 — 召剑 ','🌀 Formation — summoning '],['☝️ 凝结几何长剑 ','☝️ Forming geometric sword '],['攥紧蓄力 ','Fist charge '],['单食指确认 ','Confirming index finger '],['食指穿行','Fingertip flight'],['摊掌排剑','Open-palm formation'],['绕行剑流','Winding sword flow'],['张开释放','Open to release'],['鼠标收拢度','Mouse grip'],['粒子','Particles'],['力度','Strength'],['角度 左右','Angle: roll'],['前后','pitch'],['手势','Gesture'],['剑向','Sword angle'],['张开','Open'],['攥拳','Fist'],['剑指','Sword fingers'],['秒','s'],[' 把',' swords']
 ];
 pairs.sort((a,b)=>b[0].length-a[0].length);
 const translate=s=>pairs.reduce((v,[zh,en])=>v.split(zh).join(en),s);
 let lang='zh';try{lang=localStorage.getItem('sword-flow-language')||(/zh/i.test(navigator.language)?'zh':'en');}catch{}
 const memory=new WeakMap();
 const toggle=document.createElement('button');toggle.id='languageToggle';toggle.type='button';toggle.dataset.i18nIgnore='true';document.getElementById('bottom').prepend(toggle);
 function text(node){const current=node.nodeValue;const saved=memory.get(node);const original=saved&&current===saved.rendered?saved.original:current;const rendered=lang==='en'?translate(original):original;if(current!==rendered)node.nodeValue=rendered;memory.set(node,{original,rendered});}
 function scan(root){if(root.nodeType===3){text(root);return;}if(root.nodeType!==1||root.closest('script,style,[data-i18n-ignore]'))return;const walk=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement.closest('script,style,[data-i18n-ignore]')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});while(walk.nextNode())text(walk.currentNode);for(const el of [root,...root.querySelectorAll('[title],[aria-label]')])for(const attr of ['title','aria-label']){if(!el.hasAttribute(attr)||el.dataset.i18nIgnore)continue;const key='original'+attr.replace('-','');const source=el.dataset[key]||el.getAttribute(attr);el.dataset[key]=source;el.setAttribute(attr,lang==='en'?translate(source):source);}}
 const options={childList:true,characterData:true,subtree:true};const observer=new MutationObserver(records=>{observer.disconnect();const roots=new Set(records.map(r=>r.type==='characterData'?r.target:r.target));roots.forEach(scan);observer.observe(document.body,options);});
 function apply(){observer.disconnect();document.documentElement.lang=lang==='en'?'en':'zh-CN';toggle.textContent=lang==='en'?'中文':'English';toggle.setAttribute('aria-label',lang==='en'?'Switch to Chinese':'切换到英文');document.title=lang==='en'?'Sword Flow · Gesture Playground':'御剑实验室 · Sword Flow';scan(document.body);observer.observe(document.body,options);}
 toggle.onclick=()=>{lang=lang==='en'?'zh':'en';try{localStorage.setItem('sword-flow-language',lang);}catch{}apply();};
 window.SwordI18n={translate};apply();
})();
